name: Generate Proto Code & Commit

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Protobuf code
        uses: bufbuild/buf-action@v1
        with:
          format: true
          lint: true
          push: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download dependencies
        run: go mod download

      - name: Injest Go Tags
        run: |
          buf generate
          buf dep update
          go install github.com/favadi/protoc-go-inject-tag@latest
          find gen -name "*.pb.go" -exec protoc-go-inject-tag -input={} \;

      - name: Start services
        run: |
          docker compose up -d

      - name: Run tests
        run: |
          go test -v ./...
        env:
          ARANGO_URL: http://localhost:8529
          ARANGO_DB: test
          ARANGO_USERNAME: root
          ARANGO_PASSWORD: "0123"

      - name: Build service
        run: |
          go build -o omnibasement ./src/main.go

      - name: Show service logs
        if: always()
        run: |
          docker compose logs

      - name: Stop services
        if: always()
        run: |
          docker compose down

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: Refresh protobuf generated files in ./gen/ and ./doc/"
          commit_options: '--no-verify'
          file_pattern: 'gen/ doc/'
          branch: ${{ github.ref_name }}
